### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by ghost** [BorisGautier/aestheticDialogs#10]
A very beautiful package that I would like to use. But I can't as I must have iOS functionality. As Flutter is all about multi-platform, it would be really nice to see this package with at least SOME iOS functionality :)

**Comment by BorisGautier** [comment]
thank you for your interest in this package. for the moment it only runs on Android but an iOS version will be developed to allow all developers to take advantage of it

**Comment by ghost** [comment]
looking forward to it
